id: P000813
initial_creation_type: ocr
created_at: 5/04/2021
last_modified_at: 2021-12-17 10:12:01.381115
source_metadata:
  id: bdr:W1KG4324
  title: གསུང་འབུམ། བཅོམ་ལྡན་རིག་པའི་རལ་གྲི་
  volumes:
    d1c8d0e734074c9380ed71a6828fbda5:
      image_group_id: I1KG4382
      title: ''
      base_file: v001.txt
    bc6ac4d4bb1044fdb3c27eac0a8f8a32:
      image_group_id: I1KG4383
      title: ''
      base_file: v002.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
