id: I2346336A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-05T07:32:35+00:00'
last_modified: '2022-06-13T12:49:12.664461+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4324
  title: གསུང་འབུམ། བཅོམ་ལྡན་རིག་པའི་རལ་གྲི་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5D46:
      image_group_id: I1KG4382
      title: ''
      total_pages: ''
      order: 1
      base_file: 5D46.txt
    1D58:
      image_group_id: I1KG4383
      title: ''
      total_pages: ''
      order: 2
      base_file: 1D58.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
